### PR TITLE
Pravega cluster provisioning model

### LINKED ISSUE #14: Provisioning guidelines for Pravega clusters
**Problem description**
Create a tool to help users right-sizing a Pravega cluster deployment based on common requirements (e.g., availability, workload, performance).

**Problem location**
Pravega-tools.

**Suggestions for an improvement**
Create a provisioning model for Pravega.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
First version of a provisioning model for Pravega clusters.

**Purpose of the change**
Fixes #14.

**What the code does**
Based on an empirical analysis, we propose a simple yet complete model to figure out the necessary number of instances of each service based on some user input:
- Availability (failures to tolerate)
- Write workload (min number of Bookies)
- Latency requirements (min number of Segment Stores)
- Metadata operations, streams and clients (min number of Controllers)

Note that while the model aims at being generic, the performance-related values correspond to a specific environment (high-end bare metal cluster). For applying this model to other environments, we may need to perform some benchmarks to get the corresponding performance profile that the model takes as input.

**How to verify it**
Execute the script to verify its correct operation. The validity of the model should be checked via the provisioning of clusters following its guidelines, and in parallel, with the execution of real experiments on these cluster that match the workload requirements specified.

### CODE REVIEW

**Review by adrianmo — CHANGES_REQUESTED** [review]
@RaulGracia the script looks very good and it'll be very useful to properly size and configure Pravega. 

Just one comment, the script is only compatible with Python 2, not Python 3. As Python 2 will be deprecated in a few months, I think we should keep it compatible with Python 3.

I believe that the only issue that is preventing the script from working with Python 3 are the `print` functions. To make it compatible, replace all occurrences from `print "foo"` to `print("foo")`.

**Review by adrianmo — CHANGES_REQUESTED** [review]
Please include `*.pyc` files to the `.gitignore`. These files are automatically created when running the scripts.

**Comment by RaulGracia** [comment]
@adrianmo I have addressed your comments, please have another pass to check if there is anything missing. @sumit-bm I have slightly updated the way the numbers of Controller are estimated based on the workload. Please, have a look and exercise the model so we can merge it soon.

**Review by adrianmo — APPROVED** [review]
LGTM

**Comment by sumit-bm** [comment]
will use it and test during provisioning.

**Review by sumit-bm — APPROVED** [review]
+1

**Comment by RaulGracia** [comment]
Thanks @sumit-bm and @adrianmo. Any further issues can be addressed separately. @fpj could we merge this?

**Pull request merged**
